version: "3.9"

services:
  db:
    image: docker.arvancloud.ir/postgres
    container_name: test_project_db
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "2345:5432"
    networks:
      - test_project
    restart: no
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user" ]
      interval: 5s
      retries: 5

networks:
  test_project:
    driver: bridge
