services:
  db:
    image: docker.arvancloud.ir/postgres
    container_name: project_db
    volumes:
      - university_project_postgres_v:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - dev_project
    restart: unless-stopped

networks:
  dev_project:
    external: true
volumes:
  university_project_postgres_v:
    external: true
