// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
}

type File struct {
	ID         int32  `json:"id"`
	UploadedBy int32  `json:"uploaded_by"`
	Location   string `json:"location"`
	FileName   string `json:"file_name"`
	MimeType   string `json:"mime_type"`
	Ext        string `json:"ext"`
}

type Product struct {
	ID          int32       `json:"id"`
	CreatedBy   int32       `json:"created_by"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

type ProductImage struct {
	ProductID int32 `json:"product_id"`
	FileID    int32 `json:"file_id"`
}
